basePath: /
definitions:
  structs.ChartData:
    properties:
      datasets:
        items:
          $ref: '#/definitions/structs.ChartSubData'
        type: array
      labels:
        items:
          type: string
        type: array
    type: object
  structs.ChartSubData:
    properties:
      data:
        items:
          type: number
        type: array
      label:
        type: string
    type: object
  structs.ContainerTime:
    properties:
      hour:
        type: integer
      min:
        type: integer
      sec:
        type: integer
    type: object
  structs.Entry:
    properties:
      best_cj:
        type: number
      best_snatch:
        type: number
      bodyweight:
        type: number
      cj_1:
        type: number
      cj_2:
        type: number
      cj_3:
        type: number
      country:
        type: string
      date:
        type: string
      event:
        type: string
      gender:
        type: string
      instagram:
        type: string
      lifter_name:
        type: string
      sinclair:
        type: number
      snatch_1:
        type: number
      snatch_2:
        type: number
      snatch_3:
        type: number
      total:
        type: number
    type: object
  structs.EventsList:
    properties:
      events:
        items:
          $ref: '#/definitions/structs.SingleEventMetaData'
        type: array
    type: object
  structs.LeaderboardResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/structs.Entry'
        type: array
      size:
        type: integer
    type: object
  structs.LifterHistory:
    properties:
      graph:
        $ref: '#/definitions/structs.ChartData'
      lifts:
        items:
          $ref: '#/definitions/structs.Entry'
        type: array
      name:
        type: string
    type: object
  structs.NameSearchResults:
    properties:
      names:
        items:
          type: string
        type: array
    type: object
  structs.SingleEventMetaData:
    properties:
      date:
        type: string
      federation:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: api.openweightlifting.org
info:
  contact:
    email: euan@openweightlifting.org
    name: Euan Meston
  description: This is the API for OpenWeightlifting.org
  title: OpenWeightlifting API
  version: "1.0"
paths:
  /events:
    options:
      consumes:
      - application/json
      description: Metadata shows the name, federation and date of the event along
        with the filename in the event_data folder.
      parameters:
      - description: Start date to filter from
        in: query
        name: startdate
        type: string
      - description: End date to filter to
        in: query
        name: enddate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/structs.EventsList'
              type: array
            type: array
        "204":
          description: No Content
      summary: Fetch available event metadata within a set date range
      tags:
      - OPTIONS Requests
    post:
      consumes:
      - application/json
      description: Fetch a single event by ID and federation.
      parameters:
      - description: Federation of the event
        in: body
        name: federation
        required: true
        schema:
          type: string
      - description: ID of the event
        in: body
        name: id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/structs.Entry'
              type: array
            type: array
        "204":
          description: No Content
      summary: Fetch a single event
      tags:
      - POST Requests
  /history:
    post:
      consumes:
      - application/json
      description: Pull a lifter's history by name. The name must be an exact match
        and can be checked using the search endpoint.
      parameters:
      - description: name
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.LifterHistory'
        "204":
          description: No Content
      summary: Retrieve a lifter's history
      tags:
      - POST Requests
  /leaderboard:
    post:
      consumes:
      - application/json
      description: This is the used on the index page of the website and pulls the
        highest single lift for a lifter within the selected filter.
      parameters:
      - description: Position to begin from within the full query
        in: query
        name: start
        type: integer
      - description: Position to stop at within the full query
        in: query
        name: stop
        type: integer
      - description: Sort by either total or sinclair
        in: query
        name: sortby
        type: string
      - description: Federation or country to filter by
        in: query
        name: federation
        type: string
      - description: Weightclass to filter by
        in: query
        name: weightclass
        type: string
      - description: Year to filter by
        in: query
        name: year
        type: integer
      - description: Not currently used
        in: query
        name: startdate
        type: string
      - description: Not currently used
        in: query
        name: enddate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.LeaderboardResponse'
      summary: Main table on the index page
      tags:
      - POST Requests
  /lifter:
    post:
      consumes:
      - application/json
      description: This is used within the lifter page to display a lifter's record.
        It returns a JSON object that can be used with ChartJS without having to do
        any additional processing.
      parameters:
      - description: name
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.ChartData'
        "204":
          description: No Content
      summary: Retrieve a lifter's record for use with ChartJS
      tags:
      - POST Requests
  /search:
    get:
      consumes:
      - application/json
      description: Looks up a lifter by name and returns a list of possible matches.
        Requires a minimum of 3 characters.
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.NameSearchResults'
      summary: Search through lifter names
      tags:
      - GET Requests
  /time:
    get:
      description: Returns the current server time.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.ContainerTime'
      summary: Checking the servers localtime
      tags:
      - Utilities and Testing
schemes:
- https
swagger: "2.0"
