name: Database Update

on:
  push:
    branches: development
    # schedule:
    #     # Runs at midnight everyday
    #     - cron: '0 0 * * *'

jobs:
    update-database:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              python-version: ["3.11"]

        steps:
        - name: Check out repository
          uses: actions/checkout@v2

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
                python-version: ${{ matrix.python-version }}
        
        - name: Install dependencies from pipfile
          run: |
                cd python_tools
                python -m pip install --upgrade pip
                pip install pipenv
                pipenv install --dev

        - name: Run backend_cli.py
          run: |
                cd python_tools
                python -m pip install --upgrade pip
                pip install pipenv
                pipenv run python backend_cli.py --update all
        
        - name: Run check_db.py
          run: |
                cd python_tools
                pip install pipenv
                pipenv run python check_db.py


        - name: Create a new branch
          run: |
                git checkout -b update-branch-$(date +'%Y%m%d%H%M%S')
        
        - name: Commit and push if there are changes
          run: |
                git config --global user.name 'sjdoescoding'
                git add .
                git commit -m "Database Update" || echo "No changes to commit"
                git push origin update-branch-$(date +'%Y%m%d%H%M%S')
    
        - name: Open a pull request
          uses: repo-sync/pull-request@v2
          with:
            source_branch: update-branch-$(date +'%Y%m%d%H%M%S')
            destination_branch: 'development'
            pr_title: 'Database Update'
            pr_body: 'Database Update'
            github_token: ${{ secrets.GITHUB_TOKEN }}

