name: Deploy to Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Development Backend
        uses: behe/heroku-build@v1
        with:
          app-name: "dev-branch-backend"
          api-key: "${{secrets.HEROKU_API_KEY}}"
          path: "./backend/"
      - name: Deploy Development Frontend
        uses: behe/heroku-build@v1
        with:
          app-name: "dev-branch-frontend"
          api-key: "${{secrets.HEROKU_API_KEY}}"
          path: "./frontend/"