name: Integration Test

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Build & Run
        run: |
          cp -r event_data/ backend/
          cd backend/
          go build -o backend
          ./backend local &
          cd ../frontend/
          npm install
          npm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: frontend/coverage/cobertura-coverage.xml
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
