name: Integration Test

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Build & Run
        run: |
          cd backend/
          go build -o backend
          ./backend local &
          cd ../frontend/
          npm install
          npm run test